name          'ivanlei-awstools'
version       '1.0.0'
summary       'Puppet module for AWS tools'
description   'Puppet module for AWS tools including awscli, boto, and s3cmd'
source        'https://github.com/ivanlei/puppet-awstools.git'
project_page  'https://github.com/ivanlei/puppet-awstools'
license       'http://unlicense.org/'

dependency    'puppetlabs/stdlib', '>=4.1.0'
dependency    'ivanlei/python_pip', '>=1.0.0'
